server:
  port: 8080
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://52.78.34.107:8761/eureka/

spring:
  application:
    name: gateway-service

  cloud:
    cicuitbreaker:
      resilience4j:
        enabled: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
      routes:
        - id: user-service
          uri: http://13.209.3.108:4500/
          predicates:
            - Path=/users/**

        - id: mypage-service
          uri: http://13.209.3.108:4500/
          predicates:
            - Path=/mypage/**
          filters:
            - UserFilter

        - id: mountain-service
          uri: http://13.209.98.223:5000/
          predicates:
            - Path=/mountain

        - id: mountain-service
          uri: http://13.209.98.223:5000/
          predicates:
            - Path=/mountain/{mountainId}

        - id: mountain-service
          uri: http://13.209.98.223:5000/
          predicates:
            - Method=GET
            - Path=/mountain/{mountainId}/review

        - id: mountain-service
          uri: http://13.209.98.223:5000/
          predicates:
            - Path=/mountain/{mountainId}/**
          filters:
            - UserFilter

resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        registerHealthIndicator: true
        minimumNumberOfCalls: 5
    instances:
      testCircuitBreaker:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      slow-details: always
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    root: INFO

jwt:
  secret-key: aG9sYW0tcHJvamVjdC1zZWNyZXQta2V5LWNvZGVzdGF0ZQ==