server:
  port: 8080
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://52.78.34.107:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/join
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/mypage/myInfo
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
        - id: mountain-service
          uri: lb://MOUNTAIN-SERVICE
          predicates:
            - Path=/mountain/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: mountain-service
          uri: lb://MOUNTAIN-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - RemoveRequestHeader=Cookie

resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        registerHealthIndicator: true
        minimumNumberOfCalls: 5
    instances:
      testCircuitBreaker:
        baseConfig: default

management:
  endpoints:
    health:
      circuitbreakers:
        enabled: true
  endpoint:
    shutdown:
      enabled: true

logging:
  level:
    root: INFO

jwt:
  secret-key: aG9sYW0tcHJvamVjdC1zZWNyZXQta2V5LWNvZGVzdGF0ZQ==