server:
  port: 8080
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://52.78.34.107:8761//eureka/

spring:
  application:
    name: gateway-service

  cloud:
    cicuitbreaker:
      resilience4j:
        enabled: true
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 3s
      routes: # filter 설정
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: mountain-service
          uri: lb://MOUNTAIN-SERVICE
          predicates:
            - Path=/mountain/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: api-service
          uri: lb://MOUNTAIN-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - RemoveRequestHeader=Cookie

resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        registerHealthIndicator: true
        minimumNumberOfCalls: 5
    instances:
      testCircuitBreaker:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      slow-details: always
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    root: INFO

jwt:
  secret-key: aG9sYW0tcHJvamVjdC1zZWNyZXQta2V5LWNvZGVzdGF0ZQ==